// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLFYOYAZmXcouFG2F8akGvTTsgnWFWrg',
    appId: '1:278666888228:web:0e40969b06a200e63b04b1',
    messagingSenderId: '278666888228',
    projectId: 'esp32-connect-za',
    authDomain: 'esp32-connect-za.firebaseapp.com',
    databaseURL: 'https://esp32-connect-za-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32-connect-za.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFzgvPYtYCDC-8RNEKU4Cxcs07eg3XPfU',
    appId: '1:278666888228:android:19114fd2b4c352683b04b1',
    messagingSenderId: '278666888228',
    projectId: 'esp32-connect-za',
    databaseURL: 'https://esp32-connect-za-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32-connect-za.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmN7jb3P7hy0nuTcJjEvR6lGqbm6d51_E',
    appId: '1:278666888228:ios:7c62a1eece6765b63b04b1',
    messagingSenderId: '278666888228',
    projectId: 'esp32-connect-za',
    databaseURL: 'https://esp32-connect-za-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32-connect-za.appspot.com',
    iosBundleId: 'com.example.ledMatrix',
  );
}
